language: cpp
sudo: required
dist: trusty

compiler:
    - g++

os:
   - linux

before_install:
    - curl -s https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz | sh

before_script:
    - chmod 755 test.sh

script: ./test.sh