sudo: required

language: c++

services:
  - docker

install:
    - docker build -t thingc .

script:
    - mkdir build-output
    - docker run -v $(pwd)/build-output:/app-src/build-output -it thingc
